version: 2

deploy:
  steps:
    setupVariables:
      after:
      - name: trigger jenkins
        run: |
          echo "Executing Jenkins pipeline"
      - name: wait for jenkins jobs to complete 
        run: | 
          sleep 5