apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer | default "letsencrypt-prod" }}
    # nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - path: {{ .Values.path | default "/" }}
        pathType: {{ .Values.prefix | default "Prefix" }}
        backend:
          service:
            name: {{ .Values.serviceName }}
            port:
              number: {{ .Values.portNumber }}
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: {{ .Release.Name }}-tls

