version: 1

deploy:
  steps:
    setupVariables:
      after: &login-k8s
        - echo "$(sed 's/#USER/'"$USER"'/g' configmap.yml)" > configmap.yml;
        - cat configmap.yml
destroy:
  steps:
    setupVariables:
      after: *login-k8s
